version: 2
jobs:
  build:
    working_directory: ~/advocate-backend
    docker:
      - image: circleci/python:3.5.3

    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 ./

      - store_artifacts:
          path: test-reports
          destination: test-reports
